# 第一阶段：构建Vue前端
FROM node:18 AS web-builder
WORKDIR /app
COPY main/manager-web/package*.json ./
RUN npm install
COPY main/manager-web .
RUN npm run build

# 第二阶段：构建Java后端
FROM maven:3.9.4-eclipse-temurin-21 AS api-builder
WORKDIR /app
COPY main/manager-api/pom.xml .
COPY main/manager-api/src ./src
RUN mvn clean package -Dmaven.test.skip=true

# 第三阶段：构建最终镜像
FROM bellsoft/liberica-runtime-container:jre-21-glibc

# ⚠️ ảnh này bạn đang dùng apk, nên mình giữ nguyên cách của bạn
# cài nginx + tools
RUN apk update && \
    apk add --no-cache --no-scripts \
        nginx \
        bash \
        fontconfig \
        ttf-dejavu \
        msttcorefonts-installer \
        dos2unix \
    && ACCEPT_EULA=Y apk add --no-cache msttcorefonts-installer \
    && fc-cache -f -v \
    && rm -rf /var/cache/apk/*

    && mkdir -p /run/nginx /var/log/nginx /var/tmp/nginx /etc/nginx/conf.d

# 复制项目自带的中文字体
COPY main/manager-web/public/generator/static/fonts/*.ttf /usr/share/fonts/


# 更新字体缓存
RUN fc-cache -f -v

# 配置Nginx
COPY docs/docker/nginx.conf /etc/nginx/nginx.conf

# 复制前端构建产物
COPY --from=web-builder /app/dist /usr/share/nginx/html

# 复制Java后端JAR包
COPY --from=api-builder /app/target/xiaozhi-esp32-api.jar /app/xiaozhi-esp32-api.jar

# 启动脚本（从Windows过来的可能是CRLF）
COPY docs/docker/start.sh /start.sh

# 🔑 chuyển CRLF -> LF và cấp quyền thực thi
RUN dos2unix /start.sh && chmod +x /start.sh

EXPOSE 8002

CMD ["/start.sh"]
